FROM golang:1.23-alpine AS protoc

RUN apk add --no-cache protobuf-dev protoc git

ENV PATH="$PATH:$(go env GOPATH)/bin"
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest \
    && go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

WORKDIR /app

ENTRYPOINT ["/bin/sh", "-c"]
